### ISSUE TITLE
screenshots in readme

### ISSUE THREAD

**Issue by goyalyashpal** [matjp/jweb#1]
hi!
thanks for bringing this into world

can you share some screenshots, say, in readme file?

i have seen both: [examples/wc/wc.md], and [docs/cwebman.pdf],
but seeing a screenshot will still be much needed

https://github.com/matjp/jweb/blob/d2e0924aaa7035fc1c10f45fb7703f92fd75583d/README.md#L29

[examples/wc/wc.md]: https://github.com/matjp/jweb/blob/main/examples/wc/wc.md
[docs/cwebman.pdf]: https://github.com/matjp/jweb/blob/main/docs/cwebman.pdf

----
**edit '23.06.02:** 
with screenshot i meant showing the literate source along with generated ["tangled" code, and the "woven" formatted document][wikip/literate_prog]. That is, for a simple sample, showcasing the looks of the corresponding parts in jweb to boxed 3 files in the web (in image attached below).

[wikip/literate_prog]: https://en.wikipedia.org/wiki/Literate_programming

> ["Literate Programming"](http://www.literateprogramming.com/knuthweb.pdf) (PDF). [The Computer Journal](https://en.wikipedia.org/wiki/The_Computer_Journal). [British Computer Society](https://en.wikipedia.org/wiki/British_Computer_Society). 27 (2): 97–111. [doi](https://en.wikipedia.org/wiki/Doi_(identifier)):[10.1093/comjnl/27.2.97](https://doi.org/10.1093%2Fcomjnl%2F27.2.97). Retrieved January 4, 2009.
ref: wikip/litp cite note 1:

![image](https://github.com/matjp/jweb/assets/19423063/25875476-ae12-4a64-b415-19d9992a8d39)

----
ohkay, i think i have figured some of the stuff out. i was assuming that the jtangle's binaries would have been distributed with the extension itself. but i guess that's not the case, so, how to get the binaries? (gh releases only contained sources) or how to compile?

**Comment by goyalyashpal** [comment]
with screenshot i meant showing the literate source along with generated ["tangled" code, and the "woven" formatted document][wikip/literate_prog]

[wikip/literate_prog]: https://en.wikipedia.org/wiki/Literate_programming

**Comment by matjp** [comment]
Hi goyalyashpal,

Thanks for your interest in JWEB. 

This project is just the JWEB library, screenshots are not applicable here. Are you referring to the JWEB Editor VS Code extension https://github.com/matjp/jweb-editor ? I could add some screenshots there.

JWEB compiles to Javascript so there are no binaries. (jtangle.js in the out folder). It is published as an npm package @ https://www.npmjs.com/package/@matjp/jweb

**Comment by goyalyashpal** [comment]
> it is published as an npm package @ https://www.npmjs.com/package/@matjp/jweb

i don't have any experience with npm 😅 but i will try asap

**Comment by goyalyashpal** [comment]
ohkay, i get it... used node version is v18.15.0

```
pacman -Ss nodejs
pacboy debug -S nodejs:x
node -v
npm -v
npm list -g --depth=0
corepack enable
```

```
cd /path/to/dir
npm init --yes
```

```
npm install @matjp/jweb
```

```
codium --install-extension matjp.jweb-editor
```

```
codium .
```


![image](https://github.com/matjp/jweb/assets/19423063/bab30c49-f314-4efc-b2d8-930e840b7da5)

**Comment by goyalyashpal** [comment]
also, this issue can better be moved to that repo itself :)

https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository
