### ISSUE TITLE
support indentation (respect blank spaces)

### ISSUE THREAD

**Issue by goyalyashpal** [matjp/jweb#3]
hi again!

i was wondering if it would be possible to respect the indentation?
i know that jweb targets only 2/4 langues: c/++ , j/ts 

but i tried with python nevertheless, and it seems to be working fine otherwise
the minor remaining style issues seems to be easily recoverable by usable a python formatter, 

the only major & irrecoverable break is due to lack of indentation support.

<img src="https://github.com/matjp/jweb/assets/19423063/5e2e8b1d-719a-4096-ad07-a0fd005fd802" width=600px /><br />

thanks a lot anyway for this wonderful port.

**Comment by matjp** [comment]
I did look into including Python indentation rules in the lexer phase when I was writing JWEB , but I was not able to get it to work reliably.
This I will have to leave to others to attempt.

**Comment by goyalyashpal** [comment]
do you have any remains of your investigations from that time?

**Comment by matjp** [comment]
Sorry, no.
